# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: kevinyaro.ch
email: kjyaroch@gmail.com
description: >
  Kevin Yaroch: information and minor writings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kyaroch.github.io" # the base hostname & protocol for your site
github_username:  kyaroch
copyright_name: Kevin Yaroch
sass:
  sass_dir: _sass

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
gems: [jekyll-paginate, jekyll-feed]
